#ifndef CONFIG_HPP
#define CONFIG_HPP

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define UPDATE_INTERVAL_MS 1000

#define OUT_OF_BOUND 1000.0f

#define BACKGROUND_ID 1
#define MAIN_MENU_ID 2
#define PLANET_WET_ID 3
#define PLANET_ICE_ID 4

#endif  // !CONFIG_HPP
