name: Compile

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cmake and dependencies
        run: sudo apt-get update && sudo apt-get install -y libboost-all-dev cmake libsfml-dev protobuf-devel
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          echo "Build successful"