name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version for the release'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cmake and dependencies
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev cmake libsfml-dev protobuf-devel
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cpack .

    - name: Publish Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: build/*.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: Release ${{ github.event.inputs.version }}
        body: |
          Release ${{ github.event.inputs.version }}
