name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version for the release'
        required: true
      changelog:
        description: 'Enter major changes for the release'
        required: false

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cmake and dependencies
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev cmake libsfml-dev protobuf-compiler
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cpack .

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*.tar.gz
        asset_name: "release-${{ github.event.inputs.version }}.tar.gz"
        tag: ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.changelog }}
        file_glob: true
